# Grid-Search

>[Grid-Search](#scrollTo=QoBv84MIUa-h)

>>[1.  vamos importar o dataset](#scrollTo=_78JL1jFVQST)

>>[2.  vamos fazer o train test split](#scrollTo=bP8vEZsNl-gh)

>>[3.  vamos aplicar o GridSearchCV](#scrollTo=Z_3KDut4mKXy)

## 1.&nbsp; classificação

### 1.1.&nbsp; vamos importar o dataset

In [3]:
# vamos importar as bibliotecas
import pandas as pd
import numpy as np
# vamos importar o dataframe do ficheiro .csv
df_student_pass = pd.read_csv("C:/Users/yfreitas/Documents/pythonSamples/Machine Learning/Files/student-mat-pass-or-fail.csv")

In [4]:

# veja as 5 primeiras linhas do dataframe
df_student_pass.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,traveltime,studytime,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,pass
0,1,1,18,1,0,0,4,4,2,2,...,3,4,1,1,3,6,5,6,6,0
1,1,1,17,1,0,1,1,1,1,2,...,3,3,1,1,3,4,5,5,6,0
2,1,1,15,1,1,1,1,1,1,2,...,3,2,2,3,3,10,7,8,10,1
3,1,1,15,1,0,1,4,2,1,3,...,2,2,1,1,5,2,15,14,15,1
4,1,1,16,1,0,1,3,3,1,2,...,3,2,1,2,5,4,6,10,10,1

In [5]:
# veja a forma do dataframe: quantas linhas, quantas colunas?
df_student_pass.shape
# veja a informação sobre o dataframe
df_student_pass.info()
# veja a descrição das variáveis numéricas
df_student_pass.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    int64
 1   sex         395 non-null    int64
 2   age         395 non-null    int64
 3   address     395 non-null    int64
 4   famsize     395 non-null    int64
 5   Pstatus     395 non-null    int64
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   traveltime  395 non-null    int64
 9   studytime   395 non-null    int64
 10  failures    395 non-null    int64
 11  schoolsup   395 non-null    int64
 12  famsup      395 non-null    int64
 13  paid        395 non-null    int64
 14  activities  395 non-null    int64
 15  nursery     395 non-null    int64
 16  higher      395 non-null    int64
 17  internet    395 non-null    int64
 18  romantic    395 non-null    int64
 19  famrel      395 non-null    int64
 20  freetime    395 non-null    int64
 21  goout       395 non-null    int64
 22  Dalc        395 non-null    int64
 23  Walc        395 non-null    int64
 24  health      395 non-null    int64
 25  absences    395 non-null    int64
 26  G1          395 non-null    int64
 27  G2          395 non-null    int64
 28  G3          395 non-null    int64
 29  pass        395 non-null    int64
dtypes: int64(30)
memory usage: 92.7 KB

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,traveltime,studytime,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,pass
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,...,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,0.883544,0.526582,16.696203,0.777215,0.288608,0.896203,2.749367,2.521519,1.448101,2.035443,...,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190,0.670886
std,0.321177,0.499926,1.276043,0.416643,0.453690,0.305384,1.094735,1.088201,0.697505,0.839240,...,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443,0.470487
min,0.000000,0.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,16.000000,1.000000,0.000000,1.000000,2.000000,2.000000,1.000000,1.000000,...,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000,0.000000
50%,1.000000,1.000000,17.000000,1.000000,0.000000,1.000000,3.000000,2.000000,1.000000,2.000000,...,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000,1.000000
75%,1.000000,1.000000,18.000000,1.000000,1.000000,1.000000,4.000000,3.000000,2.000000,2.000000,...,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000,1.000000
max,1.000000,1.000000,22.000000,1.000000,1.000000,1.000000,4.000000,4.000000,4.000000,4.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000,1.000000

In [6]:
# Count the occurrences of each unique value in the 'pass' column
pass_counts = df_student_pass['pass'].value_counts()

# Display the counts
print(pass_counts)

pass
1    265
0    130
Name: count, dtype: int64

### 1.2.&nbsp; vamos fazer o train test split

In [7]:
# defina a variável alvo
target_variable = 'pass'

# train_test split usando a função train_test_split
X = df_student_pass.drop(["G3", target_variable], axis = 1)
y = df_student_pass[target_variable]*1

# importe a função train_test_split e defina X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.2,
                                                    random_state = 12,
                                                    stratify = y)

### 1.3.&nbsp; vamos aplicar o GridSearchCV, with stratifiedKfold because it is classification RFC

In [8]:
# Vamos importar as bibliotecas
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score,
    make_scorer
)

# Vamos definir o cv
skf = StratifiedKFold(n_splits=5)

# Vamos definir o modelo de Random Forest
rf = RandomForestClassifier(random_state=42)

# Vamos definir a grid para os hyperparameters
param_grid_rf = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10]
}

# Vamos definir as métricas de scoring
scoring = {
    'accuracy': 'accuracy',
    'roc_auc': 'roc_auc'
}

# Vamos aplicar a grid search ao modelo de Random Forest
grid_search_rf = GridSearchCV(estimator=rf, param_grid=param_grid_rf, cv=skf, scoring=scoring, refit='roc_auc')
grid_search_rf.fit(X_train, y_train)

# Vamos ver os melhores hyperparameters
best_params_rf = grid_search_rf.best_params_
best_score_rf = grid_search_rf.best_score_
print("Best Parameters for Random Forest:", best_params_rf)
print("Best Cross-Validation AUC for Random Forest:", best_score_rf)

# Vamos ver os resultados para cada combinação
pd.DataFrame(grid_search_rf.cv_results_)

Best Parameters for Random Forest: {'max_depth': None, 'min_samples_split': 10, 'n_estimators': 200}
Best Cross-Validation AUC for Random Forest: 0.966470495174814

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_split,param_n_estimators,params,split0_test_accuracy,split1_test_accuracy,...,std_test_accuracy,rank_test_accuracy,split0_test_roc_auc,split1_test_roc_auc,split2_test_roc_auc,split3_test_roc_auc,split4_test_roc_auc,mean_test_roc_auc,std_test_roc_auc,rank_test_roc_auc
0,0.049735,0.000317,0.007153,0.000399,None,2,50,"{'max_depth': None, 'min_samples_split': 2, 'n...",0.859375,0.904762,...,0.033870,27,0.970100,0.973356,0.941043,0.987528,0.909884,0.956382,0.027726,34
1,0.097907,0.001480,0.010297,0.000808,None,2,100,"{'max_depth': None, 'min_samples_split': 2, 'n...",0.859375,0.920635,...,0.032348,27,0.974529,0.965986,0.944444,0.987528,0.924419,0.959381,0.022409,26
2,0.191840,0.001053,0.016988,0.000588,None,2,200,"{'max_depth': None, 'min_samples_split': 2, 'n...",0.875000,0.936508,...,0.030543,8,0.977298,0.972222,0.948413,0.987528,0.934302,0.963953,0.019611,9
3,0.049113,0.000316,0.006805,0.000513,None,5,50,"{'max_depth': None, 'min_samples_split': 5, 'n...",0.906250,0.904762,...,0.039496,12,0.979513,0.967120,0.955782,0.990930,0.918605,0.962390,0.024863,22
4,0.098782,0.004078,0.010448,0.000338,None,5,100,"{'max_depth': None, 'min_samples_split': 5, 'n...",0.890625,0.920635,...,0.029373,1,0.981174,0.965986,0.953515,0.989796,0.924419,0.962978,0.022960,17
5,0.189524,0.000676,0.016280,0.000337,None,5,200,"{'max_depth': None, 'min_samples_split': 5, 'n...",0.875000,0.904762,...,0.030625,19,0.977852,0.975057,0.953515,0.987528,0.926744,0.964139,0.021751,5
6,0.047952,0.000478,0.007062,0.000553,None,10,50,"{'max_depth': None, 'min_samples_split': 10, '...",0.921875,0.904762,...,0.034379,4,0.984496,0.958050,0.942177,0.990930,0.920930,0.959317,0.026086,29
7,0.095143,0.000509,0.010133,0.000524,None,10,100,"{'max_depth': None, 'min_samples_split': 10, '...",0.890625,0.904762,...,0.036785,23,0.983389,0.969388,0.948980,0.988662,0.927907,0.963665,0.022543,12
8,0.194915,0.005304,0.017453,0.000816,None,10,200,"{'max_depth': None, 'min_samples_split': 10, '...",0.875000,0.904762,...,0.032617,34,0.977852,0.975057,0.951247,0.988662,0.939535,0.966470,0.018182,1
9,0.047268,0.000460,0.006780,0.000445,10,2,50,"{'max_depth': 10, 'min_samples_split': 2, 'n_e...",0.875000,0.920635,...,0.034604,16,0.972315,0.976757,0.939342,0.985261,0.919186,0.958572,0.025111,33
10,0.091978,0.000510,0.009534,0.000640,10,2,100,"{'max_depth': 10, 'min_samples_split': 2, 'n_e...",0.843750,0.936508,...,0.039144,26,0.974529,0.968254,0.943878,0.986395,0.921512,0.958913,0.023286,32
11,0.184278,0.000448,0.015825,0.000613,10,2,200,"{'max_depth': 10, 'min_samples_split': 2, 'n_e...",0.875000,0.920635,...,0.026334,16,0.975637,0.972789,0.948980,0.986395,0.930233,0.962807,0.020361,20
12,0.048414,0.002020,0.006999,0.000855,10,5,50,"{'max_depth': 10, 'min_samples_split': 5, 'n_e...",0.906250,0.904762,...,0.039496,12,0.977852,0.967120,0.955782,0.990930,0.922093,0.962755,0.023421,21
13,0.092115,0.000855,0.009628,0.000654,10,5,100,"{'max_depth': 10, 'min_samples_split': 5, 'n_e...",0.890625,0.920635,...,0.033870,11,0.981174,0.965986,0.953515,0.989796,0.925581,0.963210,0.022570,15
14,0.181526,0.000897,0.015968,0.000526,10,5,200,"{'max_depth': 10, 'min_samples_split': 5, 'n_e...",0.875000,0.904762,...,0.030625,19,0.977852,0.975057,0.953515,0.988662,0.925581,0.964133,0.022397,8
15,0.046001,0.000276,0.006906,0.000233,10,10,50,"{'max_depth': 10, 'min_samples_split': 10, 'n_...",0.921875,0.904762,...,0.034379,4,0.984496,0.960317,0.942177,0.989796,0.920930,0.959543,0.025811,25
16,0.090420,0.000810,0.009691,0.000476,10,10,100,"{'max_depth': 10, 'min_samples_split': 10, 'n_...",0.890625,0.920635,...,0.038887,18,0.983389,0.969388,0.945578,0.988662,0.927907,0.962985,0.023022,16
17,0.182231,0.002624,0.016208,0.000660,10,10,200,"{'max_depth': 10, 'min_samples_split': 10, 'n_...",0.875000,0.920635,...,0.035537,33,0.977852,0.976190,0.950113,0.988662,0.938372,0.966238,0.018832,4
18,0.049699,0.000630,0.006774,0.000387,20,2,50,"{'max_depth': 20, 'min_samples_split': 2, 'n_e...",0.859375,0.904762,...,0.033870,27,0.970100,0.973356,0.941043,0.987528,0.909884,0.956382,0.027726,34
19,0.097193,0.000716,0.010437,0.000621,20,2,100,"{'max_depth': 20, 'min_samples_split': 2, 'n_e...",0.859375,0.920635,...,0.032348,27,0.974529,0.965986,0.944444,0.987528,0.924419,0.959381,0.022409,26
20,0.194712,0.002097,0.016615,0.000290,20,2,200,"{'max_depth': 20, 'min_samples_split': 2, 'n_e...",0.875000,0.936508,...,0.030543,8,0.977298,0.972222,0.948413,0.987528,0.934302,0.963953,0.019611,9
21,0.050050,0.000453,0.007416,0.000302,20,5,50,"{'max_depth': 20, 'min_samples_split': 5, 'n_e...",0.906250,0.904762,...,0.039496,12,0.979513,0.967120,0.955782,0.990930,0.918605,0.962390,0.024863,22
22,0.095414,0.002692,0.009940,0.000465,20,5,100,"{'max_depth': 20, 'min_samples_split': 5, 'n_e...",0.890625,0.920635,...,0.029373,1,0.981174,0.965986,0.953515,0.989796,0.924419,0.962978,0.022960,17
23,0.187151,0.000740,0.016338,0.000250,20,5,200,"{'max_depth': 20, 'min_samples_split': 5, 'n_e...",0.875000,0.904762,...,0.030625,19,0.977852,0.975057,0.953515,0.987528,0.926744,0.964139,0.021751,5
24,0.047399,0.000467,0.007033,0.000471,20,10,50,"{'max_depth': 20, 'min_samples_split': 10, 'n_...",0.921875,0.904762,...,0.034379,4,0.984496,0.958050,0.942177,0.990930,0.920930,0.959317,0.026086,29
25,0.092774,0.000419,0.009667,0.000342,20,10,100,"{'max_depth': 20, 'min_samples_split': 10, 'n_...",0.890625,0.904762,...,0.036785,23,0.983389,0.969388,0.948980,0.988662,0.927907,0.963665,0.022543,12
26,0.183719,0.000415,0.016055,0.000532,20,10,200,"{'max_depth': 20, 'min_samples_split': 10, 'n_...",0.875000,0.904762,...,0.032617,34,0.977852,0.975057,0.951247,0.988662,0.939535,0.966470,0.018182,1
27,0.048513,0.000658,0.007127,0.000701,30,2,50,"{'max_depth': 30, 'min_samples_split': 2, 'n_e...",0.859375,0.904762,...,0.033870,27,0.970100,0.973356,0.941043,0.987528,0.909884,0.956382,0.027726,34
28,0.095101,0.000779,0.010157,0.000463,30,2,100,"{'max_depth': 30, 'min_samples_split': 2, 'n_e...",0.859375,0.920635,...,0.032348,27,0.974529,0.965986,0.944444,0.987528,0.924419,0.959381,0.022409,26
29,0.194349,0.004693,0.016571,0.001032,30,2,200,"{'max_depth': 30, 'min_samples_split': 2, 'n_e...",0.875000,0.936508,...,0.030543,8,0.977298,0.972222,0.948413,0.987528,0.934302,0.963953,0.019611,9
30,0.049858,0.000767,0.006659,0.000897,30,5,50,"{'max_depth': 30, 'min_samples_split': 5, 'n_e...",0.906250,0.904762,...,0.039496,12,0.979513,0.967120,0.955782,0.990930,0.918605,0.962390,0.024863,22
31,0.097087,0.000569,0.010046,0.000474,30,5,100,"{'max_depth': 30, 'min_samples_split': 5, 'n_e...",0.890625,0.920635,...,0.029373,1,0.981174,0.965986,0.953515,0.989796,0.924419,0.962978,0.022960,17
32,0.189879,0.000950,0.016361,0.000628,30,5,200,"{'max_depth': 30, 'min_samples_split': 5, 'n_e...",0.875000,0.904762,...,0.030625,19,0.977852,0.975057,0.953515,0.987528,0.926744,0.964139,0.021751,5
33,0.048376,0.000535,0.006739,0.000174,30,10,50,"{'max_depth': 30, 'min_samples_split': 10, 'n_...",0.921875,0.904762,...,0.034379,4,0.984496,0.958050,0.942177,0.990930,0.920930,0.959317,0.026086,29
34,0.095333,0.000726,0.009944,0.000308,30,10,100,"{'max_depth': 30, 'min_samples_split': 10, 'n_...",0.890625,0.904762,...,0.036785,23,0.983389,0.969388,0.948980,0.988662,0.927907,0.963665,0.022543,12
35,0.187368,0.001246,0.016189,0.000869,30,10,200,"{'max_depth': 30, 'min_samples_split': 10, 'n_...",0.875000,0.904762,...,0.032617,34,0.977852,0.975057,0.951247,0.988662,0.939535,0.966470,0.018182,1

### 1.4. Predict with the best result from grid search

In [7]:
# Vamos fazer o fit do melhor modelo de Random Forest
best_rf = grid_search_rf.best_estimator_
y_pred_rf = best_rf.predict(X_test)
y_pred_rf_proba = best_rf.predict_proba(X_test)[:, 1]

# Vamos avaliar as métricas finais
print("\nRandom Forest Model Evaluation")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("AUC-ROC:", roc_auc_score(y_test, y_pred_rf_proba))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

Random Forest Model Evaluation
Accuracy: 0.9367088607594937
AUC-ROC: 0.9912917271407837
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.88      0.90        26
           1       0.94      0.96      0.95        53

    accuracy                           0.94        79
   macro avg       0.93      0.92      0.93        79
weighted avg       0.94      0.94      0.94        79

Confusion Matrix:
 [[23  3]
 [ 2 51]]

In [13]:
comparison_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_rf})
print(comparison_df.head(50))

     Actual  Predicted
208       1          1
161       0          0
126       1          1
373       0          0
228       0          0
248       0          0
291       1          1
222       1          1
51        1          1
271       1          1
22        1          1
292       1          1
134       0          0
210       0          0
308       1          1
145       1          1
310       0          0
176       1          1
130       0          0
170       0          0
96        1          1
192       0          0
94        1          1
358       1          1
266       1          0
162       0          0
394       0          0
41        1          1
0         0          0
123       1          1
124       0          0
163       1          1
63        0          0
258       1          1
12        1          1
189       1          0
342       1          1
382       1          1
27        1          1
225       0          0
154       1          1
327       1          1
263       0          0
337       0          0
309       1          1
319       1          1
129       1          1
232       0          1
10        0          0
381       0          0

In [2]:
from sklearn.metrics import confusion_matrix
# Confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred_rf)
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

NameError: name 'y_test' is not defined